### ISSUE TITLE
Dotfile for fzf

### ISSUE THREAD

**Issue by mparrett** [statico/dotfiles#11]
Hi Ian,

Thanks for sharing your writing and code.

Do you use a specific fzf config? (As mentioned [here](https://github.com/statico/dotfiles/blob/fab418f72c4b774c9592710b210f4365cd8a1bba/.vim/vimrc#L277))

If so, would you be willing to share any customizations via your dotfiles repo?

Best,
Matt Parrett

**Comment by statico** [comment]
I looked through my backups and can't find any reference to a `~/.fzf` directory other than one host where I had FZF built locally there. So, no idea!

**Comment by mparrett** [comment]
Thank you, @statico !
