### ISSUE TITLE
Error running `<C-e>`

### ISSUE THREAD

**Issue by diego898** [statico/dotfiles#8]
I am new to vim and tried the following line:

```
" You don't know what you're missing if you don't use this.
nmap <C-e> :e#<CR>
```

and got the following error:

```
E194: No alternate file name to substitute for '#'
```

**Comment by statico** [comment]
Ah, sorry that's not clearer. You need to have opened at least two buffers in Vim. You can read more about this approach in my first Vim article: https://statico.github.io/vim.html#vim-the-terminal-buffers-and-you

**Comment by diego898** [comment]
When I launch it with:

```
vim foo.txt bar.txt quux.txt quuxi.txt
```

and then try it, it still throws the same error

**Comment by statico** [comment]
Right, you have to edit another file from within Vim first. Try running that command and doing `:next` from within Vim, then try `Ctrl-e` again.
