### ISSUE TITLE
Help Vim Setting

### ISSUE THREAD

**Issue by harencode** [statico/dotfiles#9]
![image](https://user-images.githubusercontent.com/12387192/43696008-2ac5f896-9966-11e8-9e21-74cdf78d3c0b.png)

sir, i followed your blog post on https://statico.github.io/vim3.html i think all it's set but can you help me to how to remove annonying block color on empty space

**Comment by harencode** [comment]
![image](https://user-images.githubusercontent.com/12387192/43696277-66aa91ae-9967-11e8-9411-241fbf456840.png)

also how to change my line number color

**Comment by statico** [comment]
Please see `:help 'list` and `:help :highlight` from within vim.
